[package]
name = "punchtop"
version = "0.1.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]

[dependencies]
floating-duration = "0.1.2"
hostname = "^0.1"
mdns = "*"
mp3-duration = "*"
nom = "4"
rand = "*"
rodio = "*"
rust_cast = "*"
taglib = "*"
walkdir = "2"
